breed_info = {
    "affenpinscher": "Affenpinschers are small, sturdy dogs with a lively and confident personality. Known for their monkey-like expression and curious nature, they make affectionate companions.",
    "afghan_hound": "Afghan Hounds are elegant, dignified dogs with long, silky coats and an independent spirit. They are known for their grace and aloof temperament.",
    "african": "African dogs, such as the Africanis, are hardy, adaptable, and intelligent, often used as working and companion animals in their native regions.",
    "airedale": "Airedale Terriers are versatile, energetic, and intelligent, often called the 'King of Terriers'. They are friendly, courageous, and make excellent family pets.",
    "akita": "Akitas are large, powerful dogs with a noble and loyal character. Known for their courage and strong protective instincts, they are devoted to their families.",
    "american_terrier": "American Terriers, including the American Staffordshire, are muscular, intelligent, and confident, known for their loyalty and playful spirit.",
    "appenzeller": "Appenzeller Sennenhunds are active, versatile working dogs from Switzerland. They are alert, devoted, and excel as herding and family dogs.",
    "australian_cattledog": "Australian Cattle Dogs are energetic and intelligent herders, known for their loyalty and tireless work ethic. They thrive with plenty of activity and mental stimulation.",
    "australian_terrier": "Australian Terriers are spirited, alert, and courageous small dogs with a friendly disposition, making them excellent companions.",
    "basenji": "Basenjis are small, athletic dogs famed for their barkless nature. Intelligent and independent, they are clean and affectionate with their families.",
    "basset_hound": "Basset Hounds are gentle, laid-back, and friendly with an excellent sense of smell. Their calm demeanor makes them good companions for families.",
    "beagle": "Beagles are small, energetic hounds with a keen nose and playful personality. They are sociable, curious, and well-suited for family life.",
    "bedlington_terrier": "Bedlington Terriers are graceful, intelligent dogs with a unique lamb-like appearance. They are affectionate, lively, and make loving pets.",
    "bernese_mountain": "Bernese Mountain Dogs are large, friendly, and affectionate. They have a gentle temperament and are known for their loyalty and good nature.",
    "bichon_frise": "Bichon Frises are cheerful, affectionate little dogs with a fluffy white coat. They are playful, gentle, and get along well with people and other pets.",
    "blenheim_spaniel": "Blenheim Spaniels, also known as Cavalier King Charles, are affectionate, gentle toy dogs, beloved for their sweet nature and expressive faces.",
    "blood_hound": "Bloodhounds are large scent hounds with exceptional tracking abilities. They are gentle, affectionate, and determined trackers.",
    "bluetick": "Bluetick Coonhounds are friendly, intelligent, and vocal hounds with a striking blue-mottled coat. They are skilled trackers and devoted companions.",
    "border_collie": "Border Collies are highly intelligent, energetic, and trainable herding dogs, renowned for their athleticism and work ethic.",
    "border_terrier": "Border Terriers are brave, affectionate, and energetic small dogs, valued for their friendly demeanor and adaptability as family companions.",
    "borzoi": "Borzoi are graceful, elegant sighthounds with a gentle and independent spirit. They are known for their speed and quiet disposition.",
    "boston_bulldog": "Boston Bulldogs, or Boston Terriers, are compact, muscular, and friendly dogs known for their tuxedo-like appearance and lively nature.",
    "bouvier": "Bouviers des Flandres are strong, rugged working dogs with a calm and protective personality. They are loyal and versatile farm dogs.",
    "boxer": "Boxers are energetic, playful, and affectionate dogs with a muscular build and boundless enthusiasm. They are loyal family companions.",
    "brabancon": "Brabancons, or Brussels Griffons, are small, lively dogs known for their expressive faces and affectionate, alert personalities.",
    "briard": "Briards are intelligent, devoted French herding dogs with a protective streak and a distinctive, shaggy coat.",
    "brittany_spaniel": "Brittany Spaniels are cheerful, agile, and intelligent sporting dogs, prized for their hunting ability and affectionate nature.",
    "bull_mastiff": "Bullmastiffs are powerful, loyal, and courageous guard dogs with a calm temperament and strong protective instincts.",
    "cairn_terrier": "Cairn Terriers are spirited, curious, and sturdy small dogs. Friendly and alert, they love to dig and explore.",
    "cardigan_corgi": "Cardigan Welsh Corgis are long-bodied, strong, and playful herders. Loyal and affectionate, they are adaptable family pets.",
    "caucasian_ovcharka": "Caucasian Ovcharka are large, powerful guardian dogs from the Caucasus region, known for their bravery and protective instincts.",
    "cavapoo": "Cavapoos are friendly, intelligent, and affectionate crosses between Cavalier King Charles Spaniels and Poodles, valued as gentle companion dogs.",
    "chesapeake_retriever": "Chesapeake Bay Retrievers are tough, versatile gundogs with a loyal and intelligent temperament, known for their waterproof, wavy coat.",
    "chihuahua": "Chihuahuas are tiny, alert, and lively dogs with a bold personality packed into a small frame. Loyal and loving with their owners.",
    "chow": "Chow Chows are ancient, dignified Chinese dogs with a distinctive lion-like mane and blue-black tongue. They are loyal, aloof, and independent.",
    "clumber": "Clumber Spaniels are gentle, affectionate, and dignified sporting dogs with a heavy bone structure and friendly temperament.",
    "cockapoo": "Cockapoos are affectionate, intelligent hybrids of Cocker Spaniels and Poodles, known for their playful nature and hypoallergenic coat.",
    "cocker_spaniel": "Cocker Spaniels are gentle, affectionate, and merry dogs with expressive eyes and a silky coat. They are eager to please and great with families.",
    "coonhound": "Coonhounds are energetic, friendly hounds bred for their tracking ability and endurance. Loyal and sociable, they excel in outdoor activities.",
    "cotondetulear": "Coton de Tulear are small, cheerful companion dogs with a cotton-like coat, known for their affectionate and clownish personalities.",
    "curly_retriever": "Curly-coated Retrievers are lively, courageous gundogs with a distinctive curly coat. They are confident, intelligent, and tireless workers.",
    "dachshund": "Dachshunds are small, elongated hounds with a playful and clever personality. Known for their bold and independent spirit.",
    "dalmatian": "Dalmatians are energetic, strong, and intelligent dogs with a unique spotted coat. Outgoing and playful, they are known for their stamina.",
    "dandie_terrier": "Dandie Dinmont Terriers are small, affectionate, and independent with a distinctive topknot of hair and a spirited character.",
    "dhole": "Dholes are wild canids native to Asia, known for their intelligence, pack behavior, and high-pitched vocalizations.",
    "dingo": "Dingoes are wild dogs native to Australia, recognized for their adaptability, intelligence, and unique place in aboriginal culture.",
    "doberman": "Doberman Pinschers are sleek, powerful, and intelligent dogs with strong loyalty and protective instincts, making outstanding guard dogs.",
    "english_bulldog": "English Bulldogs are thickset, gentle, and affectionate with a wrinkled face and unmistakable appearance. Known for their calm demeanor.",
    "english_hound": "English Foxhounds are athletic, sociable, and friendly hounds bred for stamina and hunting ability.",
    "english_mastiff": "English Mastiffs are massive, dignified, and gentle giants. They are calm, affectionate, and protective companions.",
    "english_setter": "English Setters are elegant, gentle, and friendly sporting dogs, known for their stamina and agreeable nature.",
    "english_sheepdog": "Old English Sheepdogs are shaggy, loyal, and affectionate with a distinctive bobtail and a gentle, playful temperament.",
    "english_springer": "English Springer Spaniels are cheerful, energetic, and versatile gundogs loved for their friendly temperament and hunting prowess.",
    "entlebucher": "Entlebucher Mountain Dogs are energetic, agile Swiss herders with a loyal and lively personality.",
    "eskimo": "American Eskimo Dogs are fluffy, intelligent, and playful with a strong desire to please. Loyal family companions.",
    "flatcoated_retriever": "Flat-coated Retrievers are exuberant, friendly, and sociable with a glossy black coat and boundless enthusiasm for life.",
    "fox_terrier": "Fox Terriers are intelligent, energetic, and alert with a spirited character—a favorite among earthdogs.",
    "french_bulldog": "French Bulldogs are compact, affectionate, and playful companions, known for their distinctive bat-like ears and amiable temperament.",
    "german_pointer": "German Shorthaired Pointers are intelligent, versatile, and energetic gundogs with a friendly, outgoing personality.",
    "germanlonghair_pointer": "German Longhaired Pointers are gentle, adaptable, and agile with a love of outdoor activity and family life.",
    "germanshepherd": "German Shepherds are large, intelligent, and loyal. Renowned for their versatility as working and service dogs.",
    "golden_retriever": "Golden Retrievers are friendly, intelligent, and devoted. Their gentle temperament makes them excellent family companions.",
    "gordon_setter": "Gordon Setters are strong, loyal, and intelligent sporting dogs with a dignified presence and affectionate nature.",
    "great_dane": "Great Danes are gentle giants with a loving, friendly, and courageous temperament.",
    "groenendael": "Belgian Sheepdogs (Groenendael) are intelligent, alert, and versatile working dogs known for their loyalty and protective instincts.",
    "havanese": "Havanese are cheerful, lively, and intelligent. Great companions known for their friendly attitude and silky hair.",
    "husky": "Siberian Huskies are energetic, friendly, and resilient working dogs famous for their striking looks and sociable nature.",
    "ibizan_hound": "Ibizan Hounds are agile, intelligent, and gentle with a keen hunting instinct and playful demeanor.",
    "indian_bakharwal": "Bakharwal Dogs are ancient Indian mountain dogs known for guarding livestock and their innate courage.",
    "indian_chippiparai": "Chippiparai are sleek and intelligent South Indian sighthounds known for speed and loyalty.",
    "indian_gaddi": "Gaddi Kutta are large, brave, and loyal Indian mountain dogs traditionally used for herding and guarding.",
    "indian_greyhound": "Indian Greyhounds are sighthounds valued for their speed, endurance, and lean build.",
    "indian_mastiff": "Indian Mastiffs (Bully Kutta) are large, powerful, and protective, bred for guarding and working.",
    "indian_mudhol": "Mudhol Hounds are Indian sighthounds prized for speed, endurance, and hunting agility.",
    "indian_pariah": "Indian Pariah Dogs are hardy, intelligent, and adaptive native dogs, extremely loyal and healthy.",
    "indian_sheepdog": "Indian Sheepdogs are agile, intelligent dogs that excel in herding and guarding flocks.",
    "indian_spitz": "Indian Spitz are small, lively, and intelligent companion dogs with a fox-like appearance.",
    "irish_setter": "Irish Setters are friendly, energetic, and outgoing sporting dogs known for their striking red coat.",
    "irish_spaniel": "Irish Water Spaniels are intelligent, energetic, and playful, with a curly coat and strong swimming ability.",
    "irish_terrier": "Irish Terriers are courageous, energetic, and affectionate with a distinctive red coat.",
    "irish_wolfhound": "Irish Wolfhounds are gentle giants, known for their dignified, calm, and affectionate demeanor.",
    "italian_greyhound": "Italian Greyhounds are graceful, affectionate, and playful small sighthounds ideal for gentle companionship.",
    "japanese_spaniel": "Japanese Chin are elegant, charming toy dogs known for their affectionate and cat-like personalities.",
    "japanese_spitz": "Japanese Spitz are cheerful, playful, and loyal with a fluffy white coat and friendly nature.",
    "keeshond": "Keeshonds are lively, intelligent, and affectionate spitz-type dogs with a friendly 'smiling' expression.",
    "kelpie": "Kelpies are hard-working, intelligent Australian herding dogs with remarkable stamina and loyalty.",
    "kelpie_australian": "Australian Kelpies are highly energetic, intelligent herding dogs celebrated for their versatility and drive.",
    "kerryblue_terrier": "Kerry Blue Terriers are intelligent, versatile, and spirited with a distinct wavy blue coat.",
    "kombai": "Kombai are Indian working dogs known for their courage, guarding ability, and strong loyalty.",
    "komondor": "Komondors are large Hungarian flock guardians famous for their corded coats and protective instincts.",
    "kuvasz": "Kuvasz are majestic Hungarian livestock guardians, highly protective, independent, and loyal.",
    "labradoodle": "Labradoodles are affectionate, energetic crossbreeds with a low-shedding coat, loved for their intelligence and friendly temperament.",
    "labrador": "Labrador Retrievers are friendly, outgoing, and intelligent, making them one of the world's most popular dogs.",
    "lakeland_terrier": "Lakeland Terriers are lively, brave, and affectionate, bred for pursuing foxes and vermin.",
    "lapphund_finnish": "Finnish Lapphunds are intelligent, friendly, and agile family-oriented herding dogs.",
    "leonberg": "Leonbergers are gentle giants, affectionate and loyal, known for their calm and loving demeanor.",
    "lhasa": "Lhasa Apsos are independent, loyal, and watchful small companion dogs with a beautiful long coat.",
    "malamute": "Alaskan Malamutes are strong, friendly, and fiercely loyal working dogs, bred for endurance and stamina.",
    "malinois": "Belgian Malinois are intelligent, energetic, and driven, prized for their police and military work.",
    "maltese": "Maltese are gentle, playful, and loving toy dogs with a beautiful white coat and long history as companions.",
    "medium_poodle": "Medium Poodles are intelligent, versatile, and elegant with a hypoallergenic curly coat.",
    "mexicanhairless": "Xoloitzcuintli (Mexican Hairless) are loyal, calm, and intelligent with a unique hairless appearance.",
    "miniature_pinscher": "Miniature Pinschers are lively, fearless Toy dogs full of energy and curiosity.",
    "miniature_poodle": "Miniature Poodles are intelligent, friendly, and elegant companion dogs with hypoallergenic coats.",
    "mix": "Mixed breeds showcase a variety of temperaments and traits, providing unique companionship and often increased health resilience.",
    "newfoundland": "Newfoundlands are gentle giants known for their loving, patient, and heroic nature, as well as their swimming ability.",
    "norfolk_terrier": "Norfolk Terriers are alert, affectionate, and bold little dogs, great for families and city living.",
    "norwegian_buhund": "Norwegian Buhunds are cheerful, smart, and energetic spitz dogs bred for herding and guarding.",
    "norwegian_elkhound": "Norwegian Elkhounds are bold, friendly, and independent with excellent hunting instincts.",
    "norwich_terrier": "Norwich Terriers are small, affectionate dogs with an adventurous and courageous personality.",
    "otterhound": "Otterhounds are large, good-natured scent hounds with a love for water and a friendly disposition.",
    "papillon": "Papillons are lively, intelligent, and friendly toy dogs with distinctive butterfly-shaped ears.",
    "patterdale_terrier": "Patterdale Terriers are energetic, confident working terriers, known for their determination.",
    "pekinese": "Pekingese are dignified, affectionate companions with a lion-like mantled coat and independent spirit.",
    "pembroke": "Pembroke Welsh Corgis are intelligent, low-set herders with a friendly and affectionate nature.",
    "pitbull": "Pit Bulls are affectionate, strong, and intelligent, renowned for their loyalty and athleticism.",
    "plott_hound": "Plott Hounds are courageous, loyal, and athletic scent hounds, valued for their big-game hunting skills.",
    "pomeranian": "Pomeranians are extroverted, vivacious, and intelligent toy dogs with a plume-like tail and big personality.",
    "pug": "Pugs are sociable, affectionate, and mischievous, adored for their wrinkled face and playful nature.",
    "puggle": "Puggles are friendly, lively crossbreeds of Pug and Beagle, known for their affectionate personality.",
    "pyrenees": "Great Pyrenees are calm, patient, and gentle livestock guardians with a strong protective nature.",
    "redbone": "Redbone Coonhounds are energetic, sociable hunting dogs with a sweet, devoted temperament.",
    "rottweiler": "Rottweilers are confident, powerful, and loyal. They are calm, courageous, and make excellent protectors.",
    "russell_terrier": "Russell Terriers are energetic, alert, and fearless with a strong hunting instinct and friendly attitude.",
    "saluki": "Salukis are elegant, gentle, and devoted sighthounds bred for speed and endurance.",
    "samoyed": "Samoyeds are friendly, alert, and gentle sled dogs with a famously 'smiling' expression.",
    "schipperke": "Schipperkes are agile, curious, and intelligent small spitz dogs with a fox-like face.",
    "scottish_deerhound": "Scottish Deerhounds are gentle, polite, and dignified sighthounds bred for hunting deer.",
    "scottish_terrier": "Scottish Terriers are brave, dignified, and independent little terriers with a wiry coat.",
    "sealyham_terrier": "Sealyham Terriers are friendly, spirited, and courageous small terriers with a distinctive beard.",
    "sharpei": "Chinese Shar-Pei are independent, devoted, and alert, recognized for their wrinkled skin.",
    "shepherd_australian": "Australian Shepherds are intelligent, energetic, and hardworking, excelling in herding and agility sports.",
    "shetland_sheepdog": "Shetland Sheepdogs are bright, affectionate, and agile herding dogs, prized for their intelligence and loyalty.",
    "shiba": "Shiba Inu are bold, spirited, and alert Japanese dogs with a strong hunting instinct and independent nature.",
    "shihtzu": "Shih Tzus are affectionate, playful, and outgoing toy dogs with a flowing coat and cheerful personality.",
    "silky_terrier": "Silky Terriers are lively, friendly, and elegant toy dogs with a fine, silky coat.",
    "spanish_waterdog": "Spanish Water Dogs are energetic, versatile, and intelligent, excelling in herding, retrieving, and water work.",
    "staffordshire_bullterrier": "Staffordshire Bull Terriers are courageous, affectionate, and reliable, known for strong family bonds.",
    "standard_poodle": "Standard Poodles are highly intelligent, athletic, and elegant dogs with a curly, hypoallergenic coat.",
    "stbernard": "Saint Bernards are gentle, patient, and heroic giants, famed for their rescue work in the Alps.",
    "sussex_spaniel": "Sussex Spaniels are gentle, friendly, and even-tempered spaniels with a long, low build.",
    "swedish_danish": "Danish-Swedish Farmdogs are alert, lively, and friendly companions, originally bred for farm work.",
    "swiss_mountain": "Swiss Mountain Dogs are strong, loyal, and friendly breed group known for draft and farm work.",
    "tervuren": "Belgian Tervurens are intelligent, energetic, and protective, excelling at obedience and police work.",
    "tibetan_mastiff": "Tibetan Mastiffs are powerful, independent, and protective, bred to guard flocks in the Himalayas.",
    "tibetan_terrier": "Tibetan Terriers are lively, affectionate, and adaptable companions with a profuse, long coat.",
    "toy_poodle": "Toy Poodles are intelligent, alert, and playful miniature poodles with charming personalities.",
    "toy_terrier": "Toy Terriers are small, spirited, and lively dogs loved for their affectionate nature.",
    "vizsla": "Vizslas are affectionate, energetic, and trainable sporting dogs with a strong desire to be near people.",
    "walker_hound": "Treeing Walker Coonhounds are energetic, intelligent, and friendly hounds bred for trailing and treeing game.",
    "weimaraner": "Weimaraners are energetic, intelligent, and obedient. They are affectionate and excel as sporting dogs.",
    "welsh_spaniel": "Welsh Springer Spaniels are friendly, energetic, and affectionate gundogs with a cheerful outlook.",
    "welsh_terrier": "Welsh Terriers are spirited, friendly, and intelligent small dogs with a distinctive black-and-tan coat.",
    "westhighland_terrier": "West Highland White Terriers are lively, friendly, and courageous small dogs, also known as 'Westies'.",
    "wheaten_terrier": "Soft Coated Wheaten Terriers are friendly, spirited, and affectionate with a silky, wavy coat.",
    "whippet": "Whippets are gentle, athletic, and affectionate sighthounds, known for their speed and sweet disposition.",
    "yorkshire_terrier": "Yorkshire Terriers are bold, spirited, and affectionate toy dogs with a glossy, silky coat."
}
